// <auto-generated />
using System;
using System.Collections.Generic;
using GbxTools3D.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GbxTools3D.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251214163019_IncreaseCampaignNameMaxLengthTo24")]
    partial class IncreaseCampaignNameMaxLengthTo24
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GbxTools3D.Data.Entities.BlockInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("AirUnits")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("varbinary(3000)");

                    b.Property<int>("CollectionId")
                        .HasColumnType("int");

                    b.Property<byte[]>("GroundUnits")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("varbinary(3000)");

                    b.Property<bool>("HasAirHelper")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HasAirWaypoint")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HasConstructionModeHelper")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HasGroundHelper")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HasGroundWaypoint")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte?>("Height")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int?>("IconId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRoad")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("varchar(96)");

                    b.Property<string>("PylonName")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int?>("TerrainModifierId")
                        .HasColumnType("int");

                    b.ComplexProperty<Dictionary<string, object>>("SpawnLocAir", "GbxTools3D.Data.Entities.BlockInfo.SpawnLocAir#Iso4", b1 =>
                        {
                            b1.Property<float>("TX")
                                .HasColumnType("float")
                                .HasColumnName("SpawnLocAir_TX");

                            b1.Property<float>("TY")
                                .HasColumnType("float")
                                .HasColumnName("SpawnLocAir_TY");

                            b1.Property<float>("TZ")
                                .HasColumnType("float")
                                .HasColumnName("SpawnLocAir_TZ");

                            b1.Property<float>("XX")
                                .HasColumnType("float")
                                .HasColumnName("SpawnLocAir_XX");

                            b1.Property<float>("XY")
                                .HasColumnType("float")
                                .HasColumnName("SpawnLocAir_XY");

                            b1.Property<float>("XZ")
                                .HasColumnType("float")
                                .HasColumnName("SpawnLocAir_XZ");

                            b1.Property<float>("YX")
                                .HasColumnType("float")
                                .HasColumnName("SpawnLocAir_YX");

                            b1.Property<float>("YY")
                                .HasColumnType("float")
                                .HasColumnName("SpawnLocAir_YY");

                            b1.Property<float>("YZ")
                                .HasColumnType("float")
                                .HasColumnName("SpawnLocAir_YZ");

                            b1.Property<float>("ZX")
                                .HasColumnType("float")
                                .HasColumnName("SpawnLocAir_ZX");

                            b1.Property<float>("ZY")
                                .HasColumnType("float")
                                .HasColumnName("SpawnLocAir_ZY");

                            b1.Property<float>("ZZ")
                                .HasColumnType("float")
                                .HasColumnName("SpawnLocAir_ZZ");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("SpawnLocGround", "GbxTools3D.Data.Entities.BlockInfo.SpawnLocGround#Iso4", b1 =>
                        {
                            b1.Property<float>("TX")
                                .HasColumnType("float")
                                .HasColumnName("SpawnLocGround_TX");

                            b1.Property<float>("TY")
                                .HasColumnType("float")
                                .HasColumnName("SpawnLocGround_TY");

                            b1.Property<float>("TZ")
                                .HasColumnType("float")
                                .HasColumnName("SpawnLocGround_TZ");

                            b1.Property<float>("XX")
                                .HasColumnType("float")
                                .HasColumnName("SpawnLocGround_XX");

                            b1.Property<float>("XY")
                                .HasColumnType("float")
                                .HasColumnName("SpawnLocGround_XY");

                            b1.Property<float>("XZ")
                                .HasColumnType("float")
                                .HasColumnName("SpawnLocGround_XZ");

                            b1.Property<float>("YX")
                                .HasColumnType("float")
                                .HasColumnName("SpawnLocGround_YX");

                            b1.Property<float>("YY")
                                .HasColumnType("float")
                                .HasColumnName("SpawnLocGround_YY");

                            b1.Property<float>("YZ")
                                .HasColumnType("float")
                                .HasColumnName("SpawnLocGround_YZ");

                            b1.Property<float>("ZX")
                                .HasColumnType("float")
                                .HasColumnName("SpawnLocGround_ZX");

                            b1.Property<float>("ZY")
                                .HasColumnType("float")
                                .HasColumnName("SpawnLocGround_ZY");

                            b1.Property<float>("ZZ")
                                .HasColumnType("float")
                                .HasColumnName("SpawnLocGround_ZZ");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("IconId");

                    b.HasIndex("Name");

                    b.HasIndex("TerrainModifierId");

                    b.ToTable("BlockInfos");
                });

            modelBuilder.Entity("GbxTools3D.Data.Entities.BlockVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlockInfoId")
                        .HasColumnType("int");

                    b.Property<bool>("Ground")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MeshId")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<byte>("SubVariant")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("Variant")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("BlockInfoId");

                    b.HasIndex("MeshId");

                    b.ToTable("BlockVariants");
                });

            modelBuilder.Entity("GbxTools3D.Data.Entities.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CollectionId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("GameVersion")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.HasKey("Id");

                    b.HasIndex("GameVersion");

                    b.HasIndex("Name");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("GbxTools3D.Data.Entities.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DefaultZoneBlock")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("GameVersion")
                        .HasColumnType("int");

                    b.Property<int?>("IconId")
                        .HasColumnType("int");

                    b.Property<int?>("IconSmallId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SortIndex")
                        .HasColumnType("int");

                    b.Property<int>("SquareHeight")
                        .HasColumnType("int");

                    b.Property<int>("SquareSize")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VehicleAuthor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("VehicleCollection")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("IconId");

                    b.HasIndex("IconSmallId");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("GbxTools3D.Data.Entities.DataImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("DataImports");
                });

            modelBuilder.Entity("GbxTools3D.Data.Entities.Decoration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DecorationSizeId")
                        .HasColumnType("int");

                    b.Property<string>("Musics")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Remap")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Sounds")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<int?>("TerrainModifierCoveredId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DecorationSizeId");

                    b.HasIndex("Name");

                    b.HasIndex("TerrainModifierCoveredId");

                    b.ToTable("Decorations");
                });

            modelBuilder.Entity("GbxTools3D.Data.Entities.DecorationSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseHeight")
                        .HasColumnType("int");

                    b.Property<int>("CollectionId")
                        .HasColumnType("int");

                    b.Property<bool>("OffsetBlockY")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Scene")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("varchar(4096)");

                    b.Property<string>("SceneName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("SizeX")
                        .HasColumnType("int");

                    b.Property<int>("SizeY")
                        .HasColumnType("int");

                    b.Property<int>("SizeZ")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("SizeX", "SizeY", "SizeZ");

                    b.ToTable("DecorationSizes");
                });

            modelBuilder.Entity("GbxTools3D.Data.Entities.Icon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Data")
                        .HasColumnType("blob");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TexturePath")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Icons");
                });

            modelBuilder.Entity("GbxTools3D.Data.Entities.Map", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("mediumblob");

                    b.Property<int>("GameVersion")
                        .HasColumnType("int");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("MapUid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Path")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("GameVersion");

                    b.HasIndex("GroupId");

                    b.HasIndex("MapUid");

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("GbxTools3D.Data.Entities.MapGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("MapGroups");
                });

            modelBuilder.Entity("GbxTools3D.Data.Entities.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameVersion")
                        .HasColumnType("int");

                    b.Property<bool>("IsShader")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("ModifierId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("ShaderId")
                        .HasColumnType("int");

                    b.Property<int>("SurfaceId")
                        .HasColumnType("int");

                    b.Property<string>("Textures")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.HasKey("Id");

                    b.HasIndex("GameVersion");

                    b.HasIndex("ModifierId");

                    b.HasIndex("ShaderId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("GbxTools3D.Data.Entities.Mesh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("mediumblob");

                    b.Property<byte[]>("DataLQ")
                        .HasColumnType("mediumblob");

                    b.Property<byte[]>("DataSurf")
                        .HasColumnType("mediumblob");

                    b.Property<byte[]>("DataVLQ")
                        .HasColumnType("mediumblob");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(52)
                        .HasColumnType("varchar(52)");

                    b.Property<string>("Path")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.ToTable("Meshes");
                });

            modelBuilder.Entity("GbxTools3D.Data.Entities.ObjectLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<int>("MeshId")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("SoundId")
                        .HasColumnType("int");

                    b.Property<int>("VariantId")
                        .HasColumnType("int");

                    b.ComplexProperty<Dictionary<string, object>>("Loc", "GbxTools3D.Data.Entities.ObjectLink.Loc#Iso4", b1 =>
                        {
                            b1.Property<float>("TX")
                                .HasColumnType("float")
                                .HasColumnName("Loc_TX");

                            b1.Property<float>("TY")
                                .HasColumnType("float")
                                .HasColumnName("Loc_TY");

                            b1.Property<float>("TZ")
                                .HasColumnType("float")
                                .HasColumnName("Loc_TZ");

                            b1.Property<float>("XX")
                                .HasColumnType("float")
                                .HasColumnName("Loc_XX");

                            b1.Property<float>("XY")
                                .HasColumnType("float")
                                .HasColumnName("Loc_XY");

                            b1.Property<float>("XZ")
                                .HasColumnType("float")
                                .HasColumnName("Loc_XZ");

                            b1.Property<float>("YX")
                                .HasColumnType("float")
                                .HasColumnName("Loc_YX");

                            b1.Property<float>("YY")
                                .HasColumnType("float")
                                .HasColumnName("Loc_YY");

                            b1.Property<float>("YZ")
                                .HasColumnType("float")
                                .HasColumnName("Loc_YZ");

                            b1.Property<float>("ZX")
                                .HasColumnType("float")
                                .HasColumnName("Loc_ZX");

                            b1.Property<float>("ZY")
                                .HasColumnType("float")
                                .HasColumnName("Loc_ZY");

                            b1.Property<float>("ZZ")
                                .HasColumnType("float")
                                .HasColumnName("Loc_ZZ");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("SoundLoc", "GbxTools3D.Data.Entities.ObjectLink.SoundLoc#Iso4", b1 =>
                        {
                            b1.Property<float>("TX")
                                .HasColumnType("float")
                                .HasColumnName("SoundLoc_TX");

                            b1.Property<float>("TY")
                                .HasColumnType("float")
                                .HasColumnName("SoundLoc_TY");

                            b1.Property<float>("TZ")
                                .HasColumnType("float")
                                .HasColumnName("SoundLoc_TZ");

                            b1.Property<float>("XX")
                                .HasColumnType("float")
                                .HasColumnName("SoundLoc_XX");

                            b1.Property<float>("XY")
                                .HasColumnType("float")
                                .HasColumnName("SoundLoc_XY");

                            b1.Property<float>("XZ")
                                .HasColumnType("float")
                                .HasColumnName("SoundLoc_XZ");

                            b1.Property<float>("YX")
                                .HasColumnType("float")
                                .HasColumnName("SoundLoc_YX");

                            b1.Property<float>("YY")
                                .HasColumnType("float")
                                .HasColumnName("SoundLoc_YY");

                            b1.Property<float>("YZ")
                                .HasColumnType("float")
                                .HasColumnName("SoundLoc_YZ");

                            b1.Property<float>("ZX")
                                .HasColumnType("float")
                                .HasColumnName("SoundLoc_ZX");

                            b1.Property<float>("ZY")
                                .HasColumnType("float")
                                .HasColumnName("SoundLoc_ZY");

                            b1.Property<float>("ZZ")
                                .HasColumnType("float")
                                .HasColumnName("SoundLoc_ZZ");
                        });

                    b.HasKey("Id");

                    b.HasIndex("MeshId");

                    b.HasIndex("SoundId");

                    b.HasIndex("VariantId");

                    b.ToTable("ObjectLinks");
                });

            modelBuilder.Entity("GbxTools3D.Data.Entities.Sound", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioPath")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasMaxLength(16777215)
                        .HasColumnType("longblob");

                    b.Property<int>("GameVersion")
                        .HasColumnType("int");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(52)
                        .HasColumnType("varchar(52)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("Path", "GameVersion");

                    b.ToTable("Sounds");
                });

            modelBuilder.Entity("GbxTools3D.Data.Entities.TerrainModifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CollectionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("RemapFolder")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("Name");

                    b.ToTable("TerrainModifiers");
                });

            modelBuilder.Entity("GbxTools3D.Data.Entities.Texture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("mediumblob");

                    b.Property<int>("GameVersion")
                        .HasColumnType("int");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(52)
                        .HasColumnType("varchar(52)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("Path", "GameVersion");

                    b.ToTable("Textures");
                });

            modelBuilder.Entity("GbxTools3D.Data.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("CameraFar")
                        .HasColumnType("float");

                    b.Property<float>("CameraFov")
                        .HasColumnType("float");

                    b.Property<float>("CameraLookAtFactor")
                        .HasColumnType("float");

                    b.Property<float>("CameraUp")
                        .HasColumnType("float");

                    b.Property<int>("GameVersion")
                        .HasColumnType("int");

                    b.Property<int?>("IconId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("IconId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("GbxTools3D.Data.Entities.BlockInfo", b =>
                {
                    b.HasOne("GbxTools3D.Data.Entities.Collection", "Collection")
                        .WithMany("BlockInfos")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GbxTools3D.Data.Entities.Icon", "Icon")
                        .WithMany()
                        .HasForeignKey("IconId");

                    b.HasOne("GbxTools3D.Data.Entities.TerrainModifier", "TerrainModifier")
                        .WithMany()
                        .HasForeignKey("TerrainModifierId");

                    b.Navigation("Collection");

                    b.Navigation("Icon");

                    b.Navigation("TerrainModifier");
                });

            modelBuilder.Entity("GbxTools3D.Data.Entities.BlockVariant", b =>
                {
                    b.HasOne("GbxTools3D.Data.Entities.BlockInfo", "BlockInfo")
                        .WithMany("Variants")
                        .HasForeignKey("BlockInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GbxTools3D.Data.Entities.Mesh", "Mesh")
                        .WithMany()
                        .HasForeignKey("MeshId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlockInfo");

                    b.Navigation("Mesh");
                });

            modelBuilder.Entity("GbxTools3D.Data.Entities.Collection", b =>
                {
                    b.HasOne("GbxTools3D.Data.Entities.Icon", "Icon")
                        .WithMany()
                        .HasForeignKey("IconId");

                    b.HasOne("GbxTools3D.Data.Entities.Icon", "IconSmall")
                        .WithMany()
                        .HasForeignKey("IconSmallId");

                    b.Navigation("Icon");

                    b.Navigation("IconSmall");
                });

            modelBuilder.Entity("GbxTools3D.Data.Entities.Decoration", b =>
                {
                    b.HasOne("GbxTools3D.Data.Entities.DecorationSize", "DecorationSize")
                        .WithMany("Decorations")
                        .HasForeignKey("DecorationSizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GbxTools3D.Data.Entities.TerrainModifier", "TerrainModifierCovered")
                        .WithMany()
                        .HasForeignKey("TerrainModifierCoveredId");

                    b.Navigation("DecorationSize");

                    b.Navigation("TerrainModifierCovered");
                });

            modelBuilder.Entity("GbxTools3D.Data.Entities.DecorationSize", b =>
                {
                    b.HasOne("GbxTools3D.Data.Entities.Collection", "Collection")
                        .WithMany("DecorationSizes")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("GbxTools3D.Data.Entities.Map", b =>
                {
                    b.HasOne("GbxTools3D.Data.Entities.MapGroup", "Group")
                        .WithMany("Maps")
                        .HasForeignKey("GroupId");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("GbxTools3D.Data.Entities.MapGroup", b =>
                {
                    b.HasOne("GbxTools3D.Data.Entities.Campaign", "Campaign")
                        .WithMany("MapGroups")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("GbxTools3D.Data.Entities.Material", b =>
                {
                    b.HasOne("GbxTools3D.Data.Entities.TerrainModifier", "Modifier")
                        .WithMany("Materials")
                        .HasForeignKey("ModifierId");

                    b.HasOne("GbxTools3D.Data.Entities.Material", "Shader")
                        .WithMany()
                        .HasForeignKey("ShaderId");

                    b.Navigation("Modifier");

                    b.Navigation("Shader");
                });

            modelBuilder.Entity("GbxTools3D.Data.Entities.ObjectLink", b =>
                {
                    b.HasOne("GbxTools3D.Data.Entities.Mesh", "Mesh")
                        .WithMany()
                        .HasForeignKey("MeshId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GbxTools3D.Data.Entities.Sound", "Sound")
                        .WithMany()
                        .HasForeignKey("SoundId");

                    b.HasOne("GbxTools3D.Data.Entities.BlockVariant", "Variant")
                        .WithMany("ObjectLinks")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mesh");

                    b.Navigation("Sound");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("GbxTools3D.Data.Entities.TerrainModifier", b =>
                {
                    b.HasOne("GbxTools3D.Data.Entities.Collection", "Collection")
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("GbxTools3D.Data.Entities.Vehicle", b =>
                {
                    b.HasOne("GbxTools3D.Data.Entities.Icon", "Icon")
                        .WithMany()
                        .HasForeignKey("IconId");

                    b.Navigation("Icon");
                });

            modelBuilder.Entity("GbxTools3D.Data.Entities.BlockInfo", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("GbxTools3D.Data.Entities.BlockVariant", b =>
                {
                    b.Navigation("ObjectLinks");
                });

            modelBuilder.Entity("GbxTools3D.Data.Entities.Campaign", b =>
                {
                    b.Navigation("MapGroups");
                });

            modelBuilder.Entity("GbxTools3D.Data.Entities.Collection", b =>
                {
                    b.Navigation("BlockInfos");

                    b.Navigation("DecorationSizes");
                });

            modelBuilder.Entity("GbxTools3D.Data.Entities.DecorationSize", b =>
                {
                    b.Navigation("Decorations");
                });

            modelBuilder.Entity("GbxTools3D.Data.Entities.MapGroup", b =>
                {
                    b.Navigation("Maps");
                });

            modelBuilder.Entity("GbxTools3D.Data.Entities.TerrainModifier", b =>
                {
                    b.Navigation("Materials");
                });
#pragma warning restore 612, 618
        }
    }
}
