name: CI

on:
  push:
    branches: [ "main", "dev" ]
    paths: [ ".github/workflows/ci.yml", "GbxTools3D/**", "GbxTools3D.slnx", "nuget.config" ]
  pull_request:
    branches: [ "main", "dev" ]
    paths: [ ".github/workflows/ci.yml", "GbxTools3D/**", "GbxTools3D.slnx", "nuget.config" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
      
    - name: Install wasm-tools
      run: dotnet workload install wasm-tools
        
    - name: Restore dependencies
      run: dotnet restore GbxTools3D.slnx
      
    - name: Build
      run: dotnet build GbxTools3D.slnx --no-restore /p:ContinuousIntegrationBuild=true
      
    - name: Test
      run: dotnet test GbxTools3D.slnx --no-build --verbosity normal
